// <auto-generated />
using System;
using ConjuntoApiSprint6.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConjuntoApiSprint6.Migrations.SysProdutoDb
{
    [DbContext(typeof(SysProdutoDbContext))]
    partial class SysProdutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Categoria");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Categoria_Produto", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriaId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Categoria_Produto");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Cidade");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Cidade_Produto", b =>
                {
                    b.Property<Guid>("CidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CidadeId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Cidade_Produto");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("UF");

                    b.HasKey("Id");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.LoginTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Login");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Senha");

                    b.HasKey("Id");

                    b.ToTable("LoginTable");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Nome");

                    b.Property<double>("Preco")
                        .HasColumnType("float")
                        .HasColumnName("Preco");

                    b.HasKey("Id");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Produto_Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Produto_Tag");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Tag");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Categoria_Produto", b =>
                {
                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Categoria", "categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Produto", "produto")
                        .WithMany("categorias")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Cidade", b =>
                {
                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Estado", "estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estado");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Cidade_Produto", b =>
                {
                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Cidade", "cidade")
                        .WithMany("produtos")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Produto", "produto")
                        .WithMany("cidades")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cidade");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Produto_Tag", b =>
                {
                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Produto", "produto")
                        .WithMany("Tags")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConjuntoApiSprint6.Models.SysProduto.Tag", "tag")
                        .WithMany("Produtos")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produto");

                    b.Navigation("tag");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Cidade", b =>
                {
                    b.Navigation("produtos");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Produto", b =>
                {
                    b.Navigation("categorias");

                    b.Navigation("cidades");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ConjuntoApiSprint6.Models.SysProduto.Tag", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
